#!/bin/bash

# coverage root
coverageRoot="$ULIBS_ROOT/coverage/$UVER_COVERAGE_VERSION"
coverageLib="$coverageRoot/lib/python$(majorminorver $UVER_UPYTHON_VERSION)/site-packages"

# adding libraries to the python path
export PYTHONPATH=$coverageLib:$PYTHONPATH

# executing coverage
exec upython "$coverageRoot/bin/coverage" "$@"
