#!/bin/bash

# pylama root
pylamaRoot="$ULIBS_ROOT/pylama/$UVER_PYLAMA_VERSION"
pylamaLib="$pylamaRoot/lib/python$(majorminorver $UVER_UPYTHON_VERSION)/site-packages"

# adding libraries to the python path
export PYTHONPATH=$pylamaLib:$PYTHONPATH

# executing pylama
exec upython "$pylamaRoot/bin/pylama" "$@"
