#!/bin/bash

# pytest root
pytestRoot="$( locres libs/pytest/$UVER_PYTEST_VERSION )"
pytestLib="$pytestRoot/lib/python$(majorminorver $UVER_UPYTHON_VERSION)/site-packages"

# adding libraries to the python path
export PYTHONPATH=$pytestLib:$PYTHONPATH

# executing pytest
exec upython "$pytestRoot/bin/pytest" "$@"
