#!/bin/bash

# tank library
tankLibrary="$ULIBS_ROOT/tank/$UVER_TANK_VERSION/lib/python$(majorminorver $UVER_UPYTHON_VERSION)"

# openexr library
pyopenexrLibrary="$ULIBS_ROOT/pyopenexr/$UVER_PYOPENEXR_VERSION/$UCORE_OS/$UCORE_OS_VERSION/lib/python$(majorminorver $UVER_UPYTHON_VERSION)/site-packages"
openExrLib="$ULIBS_ROOT/openexr/$UVER_OPENEXR_VERSION/lib/$UCORE_OS/$UCORE_OS_VERSION/lib"
ilmBaseLib="$ULIBS_ROOT/ilmbase/$UVER_ILMBASE_VERSION/lib/$UCORE_OS/$UCORE_OS_VERSION/lib"

# setuptools library
setuptoolsLib="$ULIBS_ROOT/setuptools/$UVER_SETUPTOOLS_VERSION/lib/python$(majorminorver $UVER_UPYTHON_VERSION)/site-packages"

# adding libraries to the python path
export PYTHONPATH=$pyopenexrLibrary:$tankLibrary:$setuptoolsLib:$PYTHONPATH

# adding libraries to the system library path
export LD_LIBRARY_PATH=$openExrLib:$ilmBaseLib:$LD_LIBRARY_PATH

# executing upython
exec "$UAPPS_ROOT/python/$UVER_UPYTHON_VERSION/bin/$UCORE_OS/$UCORE_OS_VERSION/bin/python" "$@"
